version: '3.9'
services:
  service-a:
    image: dsauer/explore-open-tracing-service-a:latest
    pull_policy: always
    ports:
      - "55680:55680"
      - "9411:9411"
      # - "6831:6831/udp"
      - "8888:8888"
      - "14268:14268"

  nginx:
    image: opentracing-contrib/nginx-opentracing
    restart: on-failure
    depends_on:
      - service-a
    networks:
      example:
        aliases:
          - nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./jaeger-config.json:/etc/jaeger-config.json
      - ./zipkin-config.json:/etc/zipkin-config.json
    expose:
      - "8081"
      - "8082"
    ports:
      - "8081:8081"
      - "8082:8082"

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=19411
    pull_policy: always
    networks:
      example:
        aliases:
          - jaeger
    expose:
      - "16686"
      - "14250"
    ports:
      - "16686:16686"
      - "14250:14250"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      example:
        aliases:
          - web
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      OT_COLLECTOR_ADDR: otel:55680

networks:
  example: {}